config/routes.rb
InTransition::Application.routes.draw do
  resources :resources

  resources :work_groups

  resources :focus_areas, :only => [:index, :show]

  resources :initiatives

  devise_for :users

  root :to => "welcome#index"

end

app/models/focus_area.rb
class FocusArea < ActiveRecord::Base
  has_friendly_id :name, :use_slug => true

  has_many :work_groups
  has_many :resources
end

app/models/initiative.rb
class Initiative < ActiveRecord::Base
  has_friendly_id :name, :use_slug => true

  has_many :work_groups
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :focus_area

  validates_length_of :title, :minimum=>3
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation

  def role_symbols
    [:user]
  end
  def login
    email
  end
end

app/models/work_group.rb
class WorkGroup < ActiveRecord::Base
  belongs_to :initiative
  belongs_to :focus_area
  
  validates_presence_of :initiative, :focus_area
  validates_length_of :name, :minimum => 5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'

  def permission_denied
    flash[:alert] = 'You are not authorized for this action.'
    redirect_to request.referrer
  end
end

app/controllers/focus_areas_controller.rb
class FocusAreasController < InheritedResources::Base
  respond_to :html
  actions :index, :show

  navigation :focus_areas

  def show
    @focus_area = FocusArea.includes({:work_groups => [:initiative]}, :resources).find(params[:id])
    respond_with(@focus_area)
  end
end

app/controllers/initiatives_controller.rb
class InitiativesController < InheritedResources::Base
  respond_to :html, :xml, :json
  filter_resource_access

  navigation :initiatives
  
  def index
    @initiatives = Initiative.includes(:work_groups)
    respond_with(@initiatives)
  end
end

app/controllers/resources_controller.rb
class ResourcesController < InheritedResources::Base
  def index
    @resources = Resource.includes(:focus_area)
    respond_with(@resources)
  end

  def create
    @resource = Resource.create(params[:resource])
    respond_with(@resource, :location => resources_url)
  end

  def update
    @resource = Resource.find(params[:id])
    @resource.update_attributes(params[:resource])
    respond_with(@resource, :location => resources_url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController # Not using InheritedResources::Base because there isn't a database model for this controller.
  layout 'no_sidebar'
  before_filter :title

  protected
    def title
      @title = "Welcome"
    end
end

app/controllers/work_groups_controller.rb
class WorkGroupsController < InheritedResources::Base
  filter_resource_access
  navigation :work_groups
  
  def index
    @work_groups = WorkGroup.includes(:initiative).includes(:focus_area)
    respond_with(@workgroups)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    name = "Transition Pittsburgh"
    return "#{@title} - #{@controller.controller_name.humanize} - #{name}" if @title
    name
  end
end

app/helpers/focus_areas_helper.rb
module FocusAreasHelper
end

app/helpers/initiatives_helper.rb
module InitiativesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/work_groups_helper.rb
module WorkGroupsHelper
end

app/views/focus_areas/index.html.haml
%h1 Focus Areas

%ul
  - @focus_areas.each do |focus|
    %li= link_to focus.name, focus

app/views/focus_areas/show.html.haml
%h1= @focus_area.name
.box
  %h2 Work Groups
  - @focus_area.work_groups.each do |group|
    = link_to "#{group.initiative.name}: #{group.name}", group
.box
  %h2 Resources
  -@focus_area.resources.each do |resource|
    = link_to resource.title, resource
.box
  %h2 People
  (coming soon)
- content_for :sidebar do
  .box
    %h1 Featured
    (none here yet)

app/views/initiatives/_form.html.haml
= form_for @initiative do |f|
  -if @initiative.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@initiative.errors.count, "error")} prohibited this initiative from being saved:"
      %ul
        - @initiative.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :location
    = f.text_field :location
  .actions
    = f.submit 'Save'

app/views/initiatives/edit.html.haml
%h1 Editing initiative

= render 'form'

= link_to 'Show', @initiative
\|
= link_to 'Back', initiatives_path

app/views/initiatives/index.html.haml
%h1 Initiatives
- content_for :sidebar do
  = link_to 'New initiative', new_initiative_path if permitted_to? :create

- @initiatives.each do |initiative|
  .box
    %h2.title
      = link_to initiative.name, initiative_url(initiative)
    .location= initiative.location
    - unless (work_groups = initiative.work_groups).empty?
      Work groups:
      - work_groups.each do |wg|
        = link_to wg.name, work_group_path(wg)
    - permitted_to? :create do
      %p
        =link_to 'Edit', edit_initiative_path(initiative)
        =link_to 'Destroy', initiative, :confirm => 'Are you sure?', :method => :delete

app/views/initiatives/new.html.haml
%h1 New initiative

= render 'form'

= link_to 'Back', initiatives_path

app/views/initiatives/show.html.haml
%h1= @initiative.name
%p
  %b Location:
  = @initiative.location

- permitted_to? :edit do
  = link_to 'Edit', edit_initiative_path(@initiative)
  \|
= link_to 'Back', initiatives_path

app/views/layouts/application.html.haml
!!!
%html(lang="en")
  %head
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html;charset=utf-8"}
    %title Test Application
    = render :partial => "shared/scripts_and_styles"
  %body.two-col.bp
    #container.container
      = render :partial => "shared/header"
      #content
        -if notice
          %p.notice= notice
        -if alert
          %p.error= alert
        = yield
      #sidebar
        - if content_for? :sidebar
          = yield :sidebar
        - else
          -# .box
          %h1 Sidebar
          (empty)
      = render :partial => "shared/footer"

app/views/layouts/no_sidebar.html.haml
!!!
%html(lang="en")
  %head
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html;charset=utf-8"}
    %title Test Application
    = render :partial => "shared/scripts_and_styles"
  %body.bp.one-col
    #container.container
      = render :partial => "shared/header"
      #content
        -if notice
          %p.notice= notice
        -if alert
          %p.error= alert
        = yield
      = render :partial => "shared/footer"

app/views/resources/_form.html.haml
= simple_form_for @resource do |f|
  -if @resource.errors.any?
    #errorExplanation.error
      = "#{pluralize(@resource.errors.count, "error")} prohibited this resource from being saved."
  .inputs
    = f.input :title
    = f.association :focus_area
    = f.input :description, :as => :text
    = f.input :url
  .actions
    = f.button :submit

app/views/resources/edit.html.haml
%h1 Editing resource

= render 'form'

= link_to 'Show', @resource
\|
= link_to 'Back', resources_path

app/views/resources/index.html.haml
%h1 Listing resources
-content_for :sidebar do
  = link_to 'New resource', new_resource_path

- @resources.each do |resource|
  .box
    %h2.title= link_to resource.title, resource
    .focus_area= link_to resource.focus_area.name, focus_area_url(resource.focus_area)
    .description= resource.description
    = link_to resource.url, resource.url
    %p
      =link_to 'Edit', edit_resource_path(resource)
      =link_to 'Destroy', resource, :confirm => 'Are you sure?', :method => :delete

app/views/resources/new.html.haml
%h1 New resource

= render 'form'

= link_to 'Back', resources_path

app/views/resources/show.html.haml
%p
  %b Title:
  = @resource.title
%p
  %b Focus area:
  = @resource.focus_area.name
%p
  %b Description:
  = @resource.description
%p
  %b Url:
  = link_to @resource.url, @resource.url

= link_to 'Edit', edit_resource_path(@resource)
\|
= link_to 'Back', resources_path

app/views/shared/_footer.html.haml
#footer
  =link_to "Home", root_url
  |
  =link_to "Register (demo)", new_user_registration_path
  |
  =link_to "Source Code", "http://github.com/jtgeibel/in_transition"

app/views/shared/_header.html.haml
#header
  %h1 TransitionPGH
  = render_navigation :level=>1
  = render_navigation :level=>2

app/views/shared/_scripts_and_styles.html.haml
= javascript_include_tag :defaults
= csrf_meta_tag
= stylesheet_link_tag 'screen.css', :media => 'screen, projection'
= stylesheet_link_tag 'print.css', :media => 'print'
/[if lt IE 8]
  = stylesheet_link_tag 'ie.css', :media => 'screen, projection'
= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=IM+Fell+Great+Primer', :media => "screen, projection"

app/views/welcome/index.html.haml
%h1 Welcome
%p All the great things about transition go here...
%p For now, this demo site shows off some various concepts for organizing information for the Transition Pittsburgh Hub.

app/views/work_groups/_form.html.haml
= simple_form_for @work_group do |f|
  -if @work_group.errors.any?
    #errorExplanation.error
      = "#{pluralize(@work_group.errors.count, "error")} prohibited this work_group from being saved."
  .inputs
    = f.input :name
    = f.input :description, :as => :text
    = f.association :initiative
    = f.association :focus_area
  .actions
    = f.button :submit

app/views/work_groups/edit.html.haml
%h1 Editing Work Group

= render 'form'

= link_to 'Show', @work_group
\|
= link_to 'Back', work_groups_path

app/views/work_groups/index.html.haml
%h1 Active Working Groups
- content_for :sidebar do
  = link_to 'New working group', new_work_group_path if permitted_to? :create

- @work_groups.each do |wg|
  .box
    %h2.title
      = link_to wg.initiative.name, initiative_url(wg.initiative)
      \:
      = link_to wg.name, wg
    .focus_area= link_to wg.focus_area.name, focus_area_url(wg.focus_area)
    .description= wg.description
    - permitted_to? :create do
      %p
        =link_to 'Edit', edit_work_group_path(wg)
        =link_to 'Destroy', wg, :confirm => 'Are you sure?', :method => :delete

app/views/work_groups/new.html.haml
%h1 New work_group

= render 'form'

= link_to 'Back', collection_path

app/views/work_groups/show.html.haml
%p
  %b Name:
  = @work_group.name
%p
  %b Description:
  = @work_group.description
%p
  %b Initiative:
  = @work_group.initiative.name

%p
  %b Focus:
  = @work_group.focus_area.name

= link_to 'Edit', edit_work_group_path
\|
= link_to 'Back', collection_path